package Util;

public class Util_Dialog {
    public String LOCATION_EXIT_THERAPY="EXIT THERAPY";
    public String LOCATION_MISSING_PARAMS="CHECK CONFIGURATION!";
    public String LOCATION_CONFIRM_SIDERAIL="CONFIRM SIDERAIL UP! PRESS START TO CONTINUE.";
    public String LOCATION_CONFIRM_CONN_FAILED="CONNECTION FAILED!";
    public String LOCATION_CONFIRM_LOCK="LOCK!";
    public String LOCATION_EMERGENCY_STOP_CONFIRM="EMERGENCY_STOP_CONFIRM";
    public String LOCATION_ACK_CON_FAIL="LOCATION_ACK_CON_FAIL";
    public String THERAPY_DONE="THERAPY DONE!";

    public String UNDER_CURRENT_CONFIRM="UNDER_CURRENT_CONFIRM";
    public String OVER_CURRENT_CONFIRM="OVER_CURRENT_CONFIRM";

}
